version: "3.9"

services:
  postgres:
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - db_config:/etc/postgresql
    entrypoint: docker-entrypoint.sh -c 'config_file=/etc/postgresql/postgresql.conf'
volumes:
  db_data:
  db_config:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "$PWD/postgres"
